// Auth action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS';
export const AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE';

// User action types
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

// Game history actions (for all games)
export const CLEAR_GAME_HISTORY = 'CLEAR_GAME_HISTORY';

// Combined history actions
export const ADD_TO_COMBINED_HISTORY = 'ADD_TO_COMBINED_HISTORY';
export const CLEAR_COMBINED_HISTORY = 'CLEAR_COMBINED_HISTORY';
export const LOAD_COMBINED_HISTORY = 'LOAD_COMBINED_HISTORY';

// Dice game action types
export const DICE_PLAY_REQUEST = 'DICE_PLAY_REQUEST';
export const DICE_PLAY_SUCCESS = 'DICE_PLAY_SUCCESS';
export const DICE_PLAY_FAILURE = 'DICE_PLAY_FAILURE';
export const DICE_RESET_RESULT = 'DICE_RESET_RESULT';
export const DICE_RESET_GAME = 'DICE_RESET_GAME';
export const DICE_CLEAR_HISTORY = 'DICE_CLEAR_HISTORY';

// Crash game action types
export const CRASH_GAME_START = 'CRASH_GAME_START';
export const CRASH_GAME_TICK = 'CRASH_GAME_TICK';
export const CRASH_GAME_CRASH = 'CRASH_GAME_CRASH';
export const CRASH_GAME_WAITING = 'CRASH_GAME_WAITING';

export const CRASH_PLACE_BET_REQUEST = 'CRASH_PLACE_BET_REQUEST';
export const CRASH_PLACE_BET_SUCCESS = 'CRASH_PLACE_BET_SUCCESS';
export const CRASH_PLACE_BET_FAILURE = 'CRASH_PLACE_BET_FAILURE';

export const CRASH_CASHOUT_REQUEST = 'CRASH_CASHOUT_REQUEST';
export const CRASH_CASHOUT_SUCCESS = 'CRASH_CASHOUT_SUCCESS';
export const CRASH_CASHOUT_FAILURE = 'CRASH_CASHOUT_FAILURE';

export const CRASH_GET_HISTORY_REQUEST = 'CRASH_GET_HISTORY_REQUEST';
export const CRASH_GET_HISTORY_SUCCESS = 'CRASH_GET_HISTORY_SUCCESS';
export const CRASH_GET_HISTORY_FAILURE = 'CRASH_GET_HISTORY_FAILURE';

export const CRASH_RESET_GAME = 'CRASH_RESET_GAME';
export const CRASH_CLEAR_HISTORY = 'CRASH_CLEAR_HISTORY';

// Mines game action types
export const MINES_START_GAME_REQUEST = 'MINES_START_GAME_REQUEST';
export const MINES_START_GAME_SUCCESS = 'MINES_START_GAME_SUCCESS';
export const MINES_START_GAME_FAILURE = 'MINES_START_GAME_FAILURE';

export const MINES_REVEAL_TILE_REQUEST = 'MINES_REVEAL_TILE_REQUEST';
export const MINES_REVEAL_TILE_SUCCESS = 'MINES_REVEAL_TILE_SUCCESS';
export const MINES_REVEAL_TILE_FAILURE = 'MINES_REVEAL_TILE_FAILURE';

export const MINES_CASHOUT_REQUEST = 'MINES_CASHOUT_REQUEST';
export const MINES_CASHOUT_SUCCESS = 'MINES_CASHOUT_SUCCESS';
export const MINES_CASHOUT_FAILURE = 'MINES_CASHOUT_FAILURE';

export const MINES_RESET_GAME = 'MINES_RESET_GAME';
export const MINES_CLEAR_HISTORY = 'MINES_CLEAR_HISTORY';

// Plinko game action types
export const PLINKO_DROP_BALL_REQUEST = 'PLINKO_DROP_BALL_REQUEST';
export const PLINKO_DROP_BALL_SUCCESS = 'PLINKO_DROP_BALL_SUCCESS';
export const PLINKO_DROP_BALL_FAILURE = 'PLINKO_DROP_BALL_FAILURE';
export const PLINKO_BALL_UPDATE = 'PLINKO_BALL_UPDATE';
export const PLINKO_BALL_LANDED = 'PLINKO_BALL_LANDED';
export const PLINKO_RESET_GAME = 'PLINKO_RESET_GAME';
export const PLINKO_SET_RISK = 'PLINKO_SET_RISK';
export const PLINKO_CLEAR_HISTORY = 'PLINKO_CLEAR_HISTORY'; 